theme: jekyll-theme-midnight
description: Author of the thrilling Australian fantasy books the Bonehead Resistance and the Bonehead Gate
show_downloads: true
github:
  tar_url: https://www.blackcockiepress.com.au/shop/#!/The-Bonehead-Resistance-Narelle-King/p/502171741/category=0
  zip_url: https://www.amazon.com.au/Bonehead-Resistance-Narelle-King/dp/0645489603/ref=mp_s_a_1_1?crid=1J39N6SA1SF72&keywords=bonehead+resistance&qid=1688680111&sprefix=the+bonehead+res%2Caps%2C292&sr=8-1
